CREATE DATABASE cadastro COLLATE utf8mb4_0900_ai_ci;
USE cadastro;

# DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME,
    PRIMARY KEY(id)
);
# TRUNCATE TABLE users;

SELECT * FROM users;

